name: Build and push image to ECR
on: push
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and tag image
      id: build-image
      run: |
        docker build -t my-docker-image .
        docker tag demorepo:latest public.ecr.aws/r3p5k7f4/demorepo:latest    
    - name: Push image to Amazon ECR
      run: |
        docker push public.ecr.aws/r3p5k7f4/demorepo:latest



# name: Upload website

# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest      docker tag my-docker-image:latest ${{ steps.login-ecr.outputs.registry }}/demorepo:sample_image
#     steps:                        docker tag demorepo:latest public.ecr.aws/r3p5k7f4/demorepo:latest
#       - uses: actions/checkout@master    docker push public.ecr.aws/r3p5k7f4/demorepo:latest
#       - uses: jakejarvis/s3-sync-action@master    docker push ${{ steps.login-ecr.outputs.registry }}/demorepo:sample_image
#         with:
#           args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
#         env:
#           AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#This should work